package ntd17.objects;

import org.openqa.selenium.WebElement;

public class Link {

    //the URL that opens when the link is clicked
    private String href;
    //the label displayed on the link
    private String label;

    //constructor for EXPECTED content; autogenerated
    public Link(String href, String label) {
        this.href = href;
        this.label = label;
    }

    //constructor for ACTUAL content
    public Link(WebElement element) {
        //the URL that opens when the link is clicked
        this.href = element.getAttribute("href");
        //the label, obtained with getText
        this.label = element.getText();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Link link = (Link) o;

        if (href != null ? !href.equals(link.href) : link.href != null) return false;
        return label != null ? label.equals(link.label) : link.label == null;
    }

    @Override
    public int hashCode() {
        int result = href != null ? href.hashCode() : 0;
        result = 31 * result + (label != null ? label.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Link{" +
                "href='" + href + '\'' +
                ", label='" + label + '\'' +
                '}';
    }
}
